### ISSUE TITLE
Disk and Service check not working

### ISSUE THREAD

**Issue by log1-c** [haxtibal/i4w_callapi#4]
Hi
first f all thanks for the effort for creating this tool. I am currently trying it out to see if this can "replace"(or better enhance) the powershell framework checks.

Second, please excuse the blant title :)

But I can't figure out how to configure the checks/check commands for the Disk and Windows Service checks to have them work correctly.
I tried configuring them close to the example with the CPU check (which worked for the memory check), but there seem to be more changes needed.

**Disk Check**
current output
![image](https://user-images.githubusercontent.com/24474580/121660743-cfd11c00-caa3-11eb-8604-88c7dfa14e40.png)
executed command line
`'C:\Program Files\ICINGA2\/sbin/call_api_check.exe' '--insecure' '-c' 'Invoke-IcingaCheckUsedPartitionSpace' '--' '-Warning' '85' '-Critical' '95' '-Include' '@()' '-Exclude' '@()'`
configured command, basically left as it came from the PowerShell Framework basket to be imported into the Icinga Director. Only changed the `-c` parameter and its position.
```
object CheckCommand "Invoke-IcingaCheckUsedPartitionSpace_api workaround" {
    import "PowerShell Base_api workaround"

    arguments += {
        "-Critical" = {
            order = 3
            value = "$IcingaCheckUsedPartitionSpace_Object_Critical$"
        }
        "-Exclude" = {
            order = 5
            value = {{
                var arr = macro("$IcingaCheckUsedPartitionSpace_Array_Exclude$");
                if (len(arr) == 0) {
                    return "@()";
                }
                return arr.map(
                    x => if (typeof(x) == String) {
                        var argLen = len(x);
                        if (argLen != 0 && x.substr(0,1) == "'" && x.substr(argLen - 1, argLen) == "'") {
                            x;
                        } else {
                            "'" + x + "'";
                        }
                    } else {
                        x;
                    }
                ).join(",");
            }}
        }
        "-IgnoreEmptyChecks" = {
            order = 99
            set_if = "$IcingaCheckUsedPartitionSpace_Switchparameter_IgnoreEmptyChecks$"
        }
        "-Include" = {
            order = 4
            value = {{
                var arr = macro("$IcingaCheckUsedPartitionSpace_Array_Include$");
                if (len(arr) == 0) {
                    return "@()";
                }
                return arr.map(
                    x => if (typeof(x) == String) {
                        var argLen = len(x);
                        if (argLen != 0 && x.substr(0,1) == "'" && x.substr(argLen - 1, argLen) == "'") {
                            x;
                        } else {
                            "'" + x + "'";
                        }
                    } else {
                        x;
                    }
                ).join(",");
            }}
        }
        "-NoPerfData" = {
            order = 99
            set_if = "$IcingaCheckUsedPartitionSpace_Switchparameter_NoPerfData$"
        }
        "-SkipUnknown" = {
            order = 99
            set_if = "$IcingaCheckUsedPartitionSpace_Switchparameter_SkipUnknown$"
        }
        "-Verbosity" = {
            order = 6
            value = "$IcingaCheckUsedPartitionSpace_Int32_Verbosity$"
        }
        "-Warning" = {
            order = 2
            value = "$IcingaCheckUsedPartitionSpace_Object_Warning$"
        }
        "-c" = {
            order = -2
            value = "Invoke-IcingaCheckUsedPartitionSpace"
        }
    }
    vars.IcingaCheckUsedPartitionSpace_Switchparameter_IgnoreEmptyChecks = false
    vars.IcingaCheckUsedPartitionSpace_Switchparameter_NoPerfData = false
    vars.IcingaCheckUsedPartitionSpace_Switchparameter_SkipUnknown = false
}
```

As the description for the "Include" parameter field states that "Used to specify an array of partitions to be included. _If not set, the check expects that all not excluded partitions should be checked_. e.g. 'C:\','D:\'" I assumed/hoped that this would still work.

Adding a single partition to the check changes the command executed, but not the outcome
`'C:\Program Files\ICINGA2\/sbin/call_api_check.exe' '--insecure' '-c' 'Invoke-IcingaCheckUsedPartitionSpace' '--' '-Warning' '85' '-Critical' '95' '-Include' ''\''C:\'\''' '-Exclude' '@()'`

**Services Check**
There might be something similar happening to the services check, because the output is as follows:
![image](https://user-images.githubusercontent.com/24474580/121662162-4c182f00-caa5-11eb-9895-cbd15ac2380b.png)
while the command executed is
`'C:\Program Files\ICINGA2\/sbin/call_api_check.exe' '--insecure' '-c' 'Invoke-IcingaCheckService' '--' '-Service' ''\''DcomLaunch'\''' '-Exclude' '@()' '-NoPerfData'`
command definition
```
object CheckCommand "Invoke-IcingaCheckService_api workaround" {
    import "PowerShell Base_api workaround"

    arguments += {
        "-Exclude" = {
            order = 3
            value = {{
                var arr = macro("$IcingaCheckService_Array_Exclude$");
                if (len(arr) == 0) {
                    return "@()";
                }
                return arr.map(
                    x => if (typeof(x) == String) {
                        var argLen = len(x);
                        if (argLen != 0 && x.substr(0,1) == "'" && x.substr(argLen - 1, argLen) == "'") {
                            x;
                        } else {
                            "'" + x + "'";
                        }
                    } else {
                        x;
                    }
                ).join(",");
            }}
        }
        "-NoPerfData" = {
            order = 99
            set_if = "$IcingaCheckService_Switchparameter_NoPerfData$"
        }
        "-Service" = {
            order = 2
            value = {{
                var arr = macro("$IcingaCheckService_Array_Service$");
                if (len(arr) == 0) {
                    return "@()";
                }
                return arr.map(
                    x => if (typeof(x) == String) {
                        var argLen = len(x);
                        if (argLen != 0 && x.substr(0,1) == "'" && x.substr(argLen - 1, argLen) == "'") {
                            x;
                        } else {
                            "'" + x + "'";
                        }
                    } else {
                        x;
                    }
                ).join(",");
            }}
        }
        "-Status" = {
            order = 4
            value = "$IcingaCheckService_String_Status$"
        }
        "-Verbosity" = {
            order = 5
            value = "$IcingaCheckService_Int32_Verbosity$"
        }
        "-c" = {
            order = -2
            value = "Invoke-IcingaCheckService"
        }
    }
    vars.IcingaCheckService_Switchparameter_NoPerfData = false
}
```

Could both be related to the Icinga Directors way of escaping stuff.
For the services check it looks to me like that the single quotes framing the service name would have to be omitted.
But I don't know how/where to implement a solution for both problems, so sorry for just saying "i doesn't work" :/

**Comment by haxtibal** [comment]
Thanks for the report. There're probably multiple unrleated issues, let's try to detangle this a bit.

First, both your Disk and Service Checks contain `@()`. Those PowerShell expressions like `@()` (empty array) or `C:,D:` (array containing strings "C:" and "D:") currently do not work via the [API](https://github.com/Icinga/icinga-powershell-apichecks). I prepared a patch to make them work, have you seen Icinga/icinga-powershell-apichecks#3 and Icinga/icinga-powershell-apichecks#4? Could you apply the pull request at your side?

The patch works for me, but not sure if @LordHepipud already managed to take a look.

Afair, the reason why that expressions work in the original `Exit-IcingaExecutePlugin` approach is that there the API call first silently fails, and then the check falls back to local execution. That second local attempt actually runs the PS parameter binder and therefore works. So, from a users perspective you won't notice the error. `call_api_check.exe` has no such fallback path, and relies on the REST API to work correctly.

**Comment by haxtibal** [comment]
Regarding the Disk Check, with Icinga/icinga-powershell-apichecks#4 applied and quotes removed, the following commands work for me in an interactive `cmd.exe`
```
> call_api_check.exe --insecure -c Invoke-IcingaCheckUsedPartitionSpace -- -Warning 85 -Critical 95 -Include @() -Exclude @()
[OK] Check package "Used Partition Space" | 'used_space_partition_c'=17.874565GB;27.199167;30.399069;0;31.999020 'partition_c'=55.85973%;85;95;0;100

> call_api_check.exe --insecure -c Invoke-IcingaCheckUsedPartitionSpace -- -Warning 85 -Critical 95 -Include C:\\ -Exclude @()
[OK] Check package "Used Partition Space" | 'used_space_partition_c'=17.875546GB;27.199167;30.399069;0;31.999020 'partition_c'=55.86279%;85;95;0;100
```

Can you try this at your side?

**Comment by haxtibal** [comment]
Regarding the Service Check, with Icinga/icinga-powershell-apichecks#4 applied and quotes removed, the following commands work for me in an interactive cmd.exe
```
> call_api_check.exe --insecure -c Invoke-IcingaCheckService -- -Service DcomLaunch -NoPerfData
[OK] Check package "Services"

> call_api_check.exe --insecure -c Invoke-IcingaCheckService -- -Service DcomLaunch -Exclude @()
[OK] Check package "Services" | 'service_dcom_server_process_launcher_dcomlaunch'=4;;4 'pending_paused_services'=0;; 'running_services'=1;; 'pending_continued_services'=0;; 'stopped_services'=0;; 'pending_started_services'=0;; 'service_count'=1;; 'pending_stopped_services'=0;; 'paused_services'=0;;
```
Can you try this at your side?

Interestingly none of the following commands work, i.e. with `-Exclude` and `-NoPerfData` combined as in your original example:
```
> call_api_check.exe --insecure -c Invoke-IcingaCheckService -- -Service DcomLaunch -Exclude @() -NoPerfData
> call_api_check.exe --insecure -c Invoke-IcingaCheckService -- -Service DcomLaunch -Exclude something -NoPerfData
> call_api_check.exe --insecure -c Invoke-IcingaCheckService -- -Service DcomLaunch -NoPerfData -Exclude something
```

Needs some further investigation.

**Comment by LordHepipud** [comment]
I honestly didn't see the PR nor the issue, sorry about that - going have a look on that,
What I am wondering is on why the arrays are not working. Has it something to do with the way you are building the arguments?

I just had a look on my test environment, which includes plenty of array checks and they work fine over the current REST-Api implementation.

**Comment by haxtibal** [comment]
@LordHepipud
> I honestly didn't see the PR nor the issue, sorry about that - going have a look on that,

No problem and no hurry. While we are at it, did you already see my other issue and patch at Icinga/icinga-powershell-restapi#3 / Icinga/icinga-powershell-restapi#4?

> What I am wondering is on why the arrays are not working. Has it something to do with the way you are building the arguments?

I've tried to describe the reason in the issue and PR description. To my understanding those expressions need the parameter binder to run in order to be "expanded". But the parameter binder doesn't run if we use splatting (as the code currently does). Therefore a `@()` is handled as ordinary string, not as array. I'm far from being an PS expert, so that assertion may be wrong.

> I just had a look on my test environment, which includes plenty of array checks and they work fine over the current REST-Api implementation.

Try running those commands with `curl.exe` and a manually crafted JSON request. You should be able to reproduce the failure then. Your PowerShell API client works because it silently falls back to local execution, where the parameter binder actually runs.

**Comment by LordHepipud** [comment]
Thanks, I will try to play around with it. I added a fallback message on the check execution, to be sure before I mentioned that.
The PowerShell handler translates the values "properly", because inside the API debugging I receive the array arguments correctly as array.

Right now all checks are executed over the API by using your threading fix. No local fallback at the moment and everything being queued and executed over the API.

That's why I'm confused about this.

**Comment by haxtibal** [comment]
@log1-c 
> Could both be related to the Icinga Directors way of escaping stuff.

Yes, likely true. Icinga Directors prepares the commands for being executed by a shell (powershell.exe). The shell interprets (and removes) quoting characters around arguments.

`call_api_check.exe` on the other hand is forked of directly from `icinga2.exe`. There's no shell magic involved. All arguments are received as-is from `argv`. If they contain quotes, the quotes are forwarded within JSON. Whether the remote side can cope with them depends on the remote side :-) I'm afraid you'll have to adapt the command definitions. I don't use the director, so can't easily test your scenarios.

**Comment by haxtibal** [comment]
@LordHepipud
> Thanks, I will try to play around with it.

Thanks too. Just wanted to suggest to switch to Icinga/icinga-powershell-apichecks#3 for array related discussion. I'm awk now, will try to have another look this weekend.

**Comment by log1-c** [comment]
Wow, that is some discussion I seem to have triggered^^

I won't pretend I understand everything about the arrays, API, JSON and stuff, but it sounds to me, that this is a somewhat bigger problem than "just replacing something somewhere".

Is it fair to say that hte i4w_callapi "workaround" is currently not suitable to be used with the Icinga Director, at least for the Disk and Service checks that expect an array, even for a single disk/service?

**Comment by haxtibal** [comment]
> Is it fair to say that hte i4w_callapi "workaround" is currently not suitable to be used with the Icinga Director

You're right, it just won't work right now (well it works for me, but only because of a bad patch).

The discussion you triggered revealed what's left to do, and I think it's actually doable.

**Comment by haxtibal** [comment]
@log1-c Would you give [0.2.0-alpha](https://github.com/haxtibal/i4w_callapi/releases/tag/0.2.0-alpha) a try? Usage is the same as before, the difference is how arguments are internally interpreted. In theory it should now work with the `arguments += { /* ...  */ }` sections generated by Icinga Director. I still have no such setup, so I'd appreciate your feedback.

**Comment by log1-c** [comment]
Hi @haxtibal 
the checks work now :)
but the load problem somewhat remains, as the avg load (on some systems at least) keeps growing over time
![image](https://user-images.githubusercontent.com/24474580/124715895-c2bd1680-df03-11eb-9dd8-69a43191deb8.png)

**Comment by haxtibal** [comment]
> the checks work now :)

@log1-c Thanks for testing!

> but the load problem somewhat remains, as the avg load (on some systems at least) keeps growing over time

@LordHepipud just today merged two maybe related PRs, see Icinga/icinga-powershell-restapi/pull/4 and Icinga/icinga-powershell-restapi/pull/5. Relating the PRs to your steadily growing load is a pure guess of mine, but "memory leak" always sounds suspicious. Would you give latest master of icinga-powershell-restapi a try?

In the mean time I'll have an eye on long time load behavior on our system. If it's reproducible, it's fixable :)

**Comment by LordHepipud** [comment]
The avg. load rising over time had multiple issues:

* Sometimes API calls were not processed due to a threading issue (thanks @haxtibal) and therefor called locally
* In some cases, the entire API could have crashed due to a memory leak, and therefore all checks were executed locally
* The old queueing system for new API requests was way more CPU intensive

We released bugfixes for the Icinga PowerShell Framework, the REST-Api and the API-Checks yesterday, which addresses all these issues: https://icinga.com/blog/2021/07/07/icinga-for-windows-v1-5-1-bugfix-release/

If you update them, this error should be gone.
