### ISSUE TITLE
Implement a PowerShell-like CLI parsing mode

### ISSUE THREAD

**Issue by haxtibal** [haxtibal/i4w_callapi#6]
As learned from Icinga/icinga-powershell-apichecks/issues/3, we (the API client) must analyze the CLI input and build the check arguments as structured JSON types. It's not sufficient to just forward the CLI args as JSON strings.

For those using the Icinga Director it's most convenient to expect the input as PowerShell arguments, because that's what we get from [the Icinga PS config generator](https://github.com/Icinga/icinga-powershell-framework/blob/master/lib/core/tools/Get-IcingaCheckCommandConfig.psm1#L434). I.e., we have to parse and deserialize a subset of PowerShell argument mode syntax.

This is absolutely not about being fully PS syntax compliant, that would almost be impossible to achieve. On the other hand, I want to support a bit more grammar rules than the current Icinga generator relies on, to be future proof, and because it's an nice exercise.

## Examples
| PS CLI Arg (as in argv)  | JSON structure | Remark |
|:-------------:|:-------------:|:-------------:|
| `-MyArg` | `{"MyArg": true}` | Switch without argument means the parameter is JSON bool true. |
| `-MyArg foo` | `{"MyArg": "foo"}` | If it looks like a string, turn it into JSON string. |
| `-MyArg "foo"` | `{"MyArg": "foo"}` | Make explicit string by enclosing in double quotes. |
| `-MyArg 123` | `{"MyArg": 123}` | If it looks like a number, turn it into a JSON number. |
| `-MyArg foo,123` | `{"MyArg": ["foo", 123]}` | Literal comma produces array... |
| `-MyArg "foo,123"` | `{"MyArg": "foo,123"}` | ...except where enclosed in quotes. |
| `-MyArg ["foo",123]` | `{"MyArg": ["foo", 123]}` | Another way to write an array is using square brackets. |
| `-MyArg @("foo",123)` | `{"MyArg": ["foo", 123]}` | Yet another way to write an array is using `@()`. |
| `-MyArg [ foo , [ 123 , 456 ] ]` | `{"MyArg": ["foo", [123, 456]]}` | Arrays can be nested. Whitespaces outside quotes are ignored. |
| `-MyArg $False,$True` | `{"MyArg": [false, true]}` | These special variables are turned into JSON bool. |
| `-MyArg '"hello, world"'` | `{"MyArg": "\"hello, world\""}` | Enclosing in single quotes prevents control character handling (except for backtick)|
| ``-MyArg "literal `" doublequote"`` | `{"MyArg": "literal \" doublequote"}` | backticks can be used to escape control characters, except if inside single quotes. |
| `-MyArg (ConvertTo-IcingaSecureString 'my string')` | `{"MyArg": "(ConvertTo-IcingaSecureString 'my string')"}` | Pass as string, the API will internally decide on what to do. |

Once done, this should fix #4.

**Comment by haxtibal** [comment]
The hardest thing about the PS syntax is that there are two ways how to create arrays
- using the comma operator (no need for quoted strings, no square brackets)
- explicit array in square brackets

Here's a stripped down context free grammar that handles both cases.
```
Grammar

Rule 0     S' -> argument
Rule 1     argument -> array
Rule 2     argument -> non_empty_element_seq_gte1
Rule 3     argument -> LITERAL
Rule 4     array -> ARRAY_START element_seq ARRAY_STOP
Rule 5     element_seq -> empty
Rule 6     element_seq -> non_empty_element_seq
Rule 7     non_empty_element_seq_gte1_start -> element COMMA
Rule 8     non_empty_element_seq_gte1 -> non_empty_element_seq_gte1_start
Rule 9     non_empty_element_seq_gte1 -> non_empty_element_seq_gte1_start non_empty_element_seq
Rule 10    non_empty_element_seq -> element
Rule 11    non_empty_element_seq -> element COMMA non_empty_element_seq
Rule 12    element -> LITERAL
Rule 13    element -> array
Rule 14    empty -> <empty>
```

A LALR parser generated with [PLY](https://www.dabeaz.com/ply/) can now recognize the following
- `a` is recognized as single character
- `a,a,a` is recognized as array of strings
- `[a,a,a]` is recognized as array of strings
- `[a,a],a,a` is recognized as array of one array and two strings

This is just to demonstrate feasibility, it does not mean the final solution its going to be a generated LALR parser, don't know yet.

**Comment by haxtibal** [comment]
The Rust side data type to take a deserialized argument can be something like
```rust
pub enum Number {
    PosInt(f64),
    NegInt(u64),
    Float(i64),
}

enum CliArgument {
    Array(Vec<CliArgument>),
    Bool(bool),
    Number(i64),
    String(String),
}
```

where `CliArgument` can be thought of a simplified form of [serde_jsons Value](https://docs.serde.rs/serde_json/value/enum.Value.html) type.

`CliArgument` shall implement [Deserialize](https://serde.rs/impl-deserialize.html) so that we can construct an new `CliArgument` from raw input by saying `let my_new_cliarg = CliArgument::deserialize(/* pass deserializer knowing the input and format here */)`.

For a `serde_json::Value` like type, it's probably not enough to mark `CliArgument` with serdes [`#[derive(Deserialize)]`](https://serde.rs/derive.html) attribute to use the default `Deserialize` implementation. They did a [specific `impl<'de> Deserialize<'de> for Value`](https://github.com/serde-rs/json/blob/master/src/value/de.rs#L16) implementation.

**Comment by haxtibal** [comment]
>  use the default Deserialize

For now I won't implement a serde format. The parser alone is enough. A serde format is going to be quite complex and it's only useful if it would be reused in other applications with other Rust-side data structures. I don't see such a reuse case coming soon.

**Comment by haxtibal** [comment]
@LordHepipud I'd appreciate your review on the PowerShell to JSON conversion examples from this issues description. Everything from that table is implemented now and covered by tests. Would you say the conversions are correct, and is it a sufficient subset of PowerShell syntax to be compatible with what Icinga Director generates. If not, what's missing?

Don't feel pushed, if you have no time to spare that's fine. Just thought you may spot some errors on first sight.

**Comment by LordHepipud** [comment]
Thank you for your effort! From what I can see, this looks fine and everything most common should be covered.

The two things I can think of right now, would be this for once:

```powershell
-MyArg (ConvertTo-IcingaSecureString 'ThisIsASecureString')
```

This should result in a string. If this also works, you should be fine.

And this:

```powershell
-MyArg @( 'test', 123 )
```

You covered the empty array, but would this also be covered? If not, I do not see the importance as besides `@()` for empty arrays, this shouldn't be used anyway. I'm just curious about it.

One more thing:

For the escaping of `\` for example: Do you require the user to escape these characters or are you doing this on code side?
In Icinga of the Director I would simply want to write

```
C:\ProgramData\icinga2\etc\icinga2\icinga2.conf
```

without having to worry on the on how it is interpreted. If this is done already, then there is nothing more I can think about.

**Comment by haxtibal** [comment]
@LordHepipud Thanks!

> ```powershell
> -MyArg (ConvertTo-IcingaSecureString 'ThisIsASecureString')
> ```

Oh, does this parentheses syntax mean "please interpret the string inside parentheses as command, then execute that command, capture stdout, and use stdout as string value for the JSON argument"?

If so, then I suppose `ConvertTo-IcingaSecureString` is some PS cmdlet, which needs a PS interpreter in place to run. Implementation options are
1. fork of a subprocess running `powershell.exe` from the Rust code, which in turn runs the `ConvertTo-IcingaSecureString` cmdlet
1. provide a hardcoded Rust replacement for `ConvertTo-IcingaSecureString` (and maybe a handful others) and do a native function call instead of spawning `powershell.exe`

As the sole reason for this project is to ged rid of `powershell.exe`, option 1 seems contradictory. Otoh, writing Rust replacements may be a never ending story, if there are more such cmd-lets. Or is `ConvertTo-IcingaSecureString` the only one that needs to be supported? How would you do it?

> This should result in a string. If this also works, you should be fine.
> 
> And this:
> 
> ```powershell
> -MyArg @( 'test', 123 )
> ```

Currently there's only support for empty array `@()`, but it should not be too hard to treat `@( 'test', 123 )` the same as `[ 'test', 123 ]` - if that's the correct interpretation.

> In Icinga of the Director I would simply want to write
> 
> ```
> C:\ProgramData\icinga2\etc\icinga2\icinga2.conf
> ```

The intention was to provide a means for escaping, but it was a misconception of mine. I'm coming from a world where `\` is used to escape things and I blindly assumed this must be the case everywhere. But it's different on Windows/PS, `\` seemingly has no special meaning there. They're using backticks to escape characters. So I have to change the escaping code to handle backticks rather then backslash.

**Comment by haxtibal** [comment]
For the record, [ConvertTo-IcingaSecureString](https://github.com/Icinga/icinga-powershell-framework/blob/master/lib/core/tools/ConvertTo-IcingaSecureString.psm1#L5) delegates to [ConvertTo-SecureString](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/convertto-securestring?view=powershell-7.1) which uses [Win32 DPAPI](https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata) to generate a "secure string". We can access DLAPI from Rust via the [winapi](https://crates.io/crates/winapi/0.2.1) crate. Did that before, it works, but the win32 API uglifies all code getting in touch with it.

**Comment by LordHepipud** [comment]
No,

```powershell
-MyArg (ConvertTo-IcingaSecureString 'ThisIsASecureString')
```

should simply be handled as string and 1:1 parsed to the API. It will internally decide on what to do.

```json
{"MyArg": "(ConvertTo-IcingaSecureString 'ThisIsASecureString')"}
```

**Comment by haxtibal** [comment]
Ok, that simplifies the task quite a bit :-)

Is this true for anything inside parentheses, or is `(ConvertTo-IcingaSecureString ...)` a special case?

**Comment by LordHepipud** [comment]
In general, this is the way on how to parse functions to an argument and should work for anything. However, we only will allow this for security reasons for `ConvertTo-IcingaSecureString` in the future, as we require this for handling passwords. As passwords could be shipped by anything, it would be the API's job to handle this.

This will ensure we cannot ship code being executed within an elevated shell.

Right now, this is not supported and will be added with the next version.
